# Generated by Django 5.2.12 on 2026-06-22 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('autor', models.CharField(default='Anônimo', max_length=100)),
                ('categoria', models.CharField(default='Motivação', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gatilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('intensidade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criterio', models.CharField(help_text='Ex: 7 dias, 30 dias', max_length=100)),
                ('dias_necessarios', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('senha_hash', models.CharField(max_length=128)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('objetivo_pessoal', models.CharField(blank=True, default='Superar meus vícios', max_length=200)),
                ('nivel_progresso', models.IntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('concluida', models.BooleanField(default=False)),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app.rotina')),
            ],
        ),
        migrations.AddField(
            model_name='rotina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='app.usuario'),
        ),
        migrations.CreateModel(
            name='RegistroGatilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('gatilho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.gatilho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_gatilho', to='app.usuario')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('prazo', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(default='geral', max_length=50)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='app.usuario')),
            ],
            options={
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=10)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='gatilho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatilhos', to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateField(default=django.utils.timezone.now)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('nivel_dependencia', models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Muito Alto', 'Muito Alto')], default='Médio', max_length=20)),
                ('data_inicio_jornada', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vicios', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='app.habito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='app.usuario')),
                ('vicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='app.vicio')),
            ],
        ),
        migrations.CreateModel(
            name='Recaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaidas', to='app.usuario')),
                ('vicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaidas', to='app.vicio')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
